---
title: "Data Catalog Schema"
author: "Mike Johnson"
date: "`r Sys.Date()`"
output: html_document
---

# Outline

The WIP catalog is intended to leverage the available opportunities with web hosted files (`FTP`, `s3`, etc), `OpenDAP` servers, and `STAC` catalogs.

Data that is dealt with is limited to 2 or 3D information presented on a rectilinear grid.

# Schema

| **Purpose** | **Name** | **Description** | **Type** | **Example VRT** | **Example OpenDap** | **Example STAC** | 
| --- | --- | ---- | ---- | ---- | ---- |
| Data | **collection** | The primary resource name, agency, or catalog of data _assets_ | string | 3DEP| GridMET | STAC Collection |
| Data | **asset** | The subdatasets or assets in the _collection_. The ID should be unique within the collection that contains the asset.| string | 30m DEM | OpenDAP endpoint | STAC asset |
| Data | **URL** |The specific access URL | string | `/vsicurl/...` | `https://...` | STAC href |
| Data | **type** |The data format reached by _URL_ | string | vrt | dap  | stac_asset |
| Data | **varname** | The filename (sans extension), or, dap varname | string | | | |
| Data | **variable** | General high order variable type | string | Land cover | Rainfall | Imagery|
| Data | **description** |Long form description of _asset_ | string | User defined | NetCDF long name| STAC Title |
| Data | **units** | The units of the values in the _asset_| string | "m" | "mm" | "wl" |
| Data | **datetime** | The reference datetime of the _asset_ if start_datetime and end_datetime are not appropriate | DATETIME  | | | |
| Data | **start_datetime** | The reference datetime of the _asset_| DATETIME  | | | |
| Data | **end_datetime** | The reference datetime of the _asset_| DATETIME  | | | |
| Data | **horizon** | The time between the datetime and the forecast datetime. Formatted as [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations), e.g. PT6H for a 6-hour forecast.| string | | | |
| Data | **deprecated** | Set this to true if a newer version of the _asset_ is available | bool | | [STAC forecast extension](https://github.com/stac-extensions/forecast#fields) - deprecated |
| Modeled Data | **model** | The name of the model generating data in _asset_ | string | NA | "CCSM4" | "CCSM4" |
| Modeled Data | **ensemble** | The _model_ ensemble member used to generate data in _asset_ | int | | | |
| Modeled Data | **scenario** | The _model_ scenario used to generate data in _asset_ | string | | | |
| Temporal Data | **duration** |The range of time covered by the asset represented as {start}/{end}, open dates are represented with `..` | string | production date or NA | OpenDap time dimension values | STAC datetime|
| Temporal Data | **accumulation_period** | Alternative to duration, If the data is not only for a specific instance in time but instead is for an accumulation over a certain period you can specify the length here.  Formatted as [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations), e.g. PT3H for a 3-hour accumulation. If not given, assumes that the forecast is for an instance in time as if this was set to P0TS (0 seconds). | production date or NA | OpenDap time dimension values | [STAC forecast extension](https://github.com/stac-extensions/forecast#fields) - forecast:accumulation_period|
| Temporal Data | **interval** | A numeric stride with a unit, built as a string | string | NA | "1 day" | STAC ... |
| Temporal Data | **T_name** | The name of the time dimension | string | | | |
| Temporal Data | **nT** | The number of time layers in the model | float | 1 | 30 | |
| Spatial Data | **X1** | The first value in the X coordinate array, typically, but not always `Xmin` | float |  | | STAC bbox element 1 |
| Spatial Data | **Xn** | The _last_ value in the `X` coordinate array, typically, but not always `Xmax` | float| | |STAC bbox element 2 |
| Spatial Data | **Y1** | The first value in the `Y` coordinate array, typically, but not always `Ymin` | float| | |STAC bbox element 3 |
| Spatial Data | **Yn** | The last value in the `Y` coordinate array, typically, but not always `Ymin` | float| | | STAC bbox element 4 |
| Spatial Data | **X_name** | The name of the `X` dimension/variable | string | | | |
| Spatial Data | **Y_name** | The name of the `Y` dimension/variable | string | | | |
| Spatial Data | **X_res** | The resolution of the data in the `X` direction `(abs(X1-Xn) / ncol)` | float | | | |
| Spatial Data | **Y_res** | The resolution of the data in the `Y` direction `(abs(Y1-Yn) / nrow)`| float | | | |
| Spatial Data | **ncol** | The number of values in the X direction `(abs(X1-Xn) / X_res)` | int | | | |
| Spatial Data | **nrow** | The number of grid cells  in the Y direction `(abs(Y1-Yn) / Y_res)`| int | | | |
| Spatial Data | **crs** | The coordinate reference system expressed as PROJ4 string | string | | | |
| Spatial Data | **epsg** | alternatve to crs, the epsg | int | | | |
| Spatial Data | **toptobottom** | Specific to OpenDap data describing the arrangement of the unfolded vector | string | | | |
| Spatial Data | **tiled** | is data tiled spatially (XY), temporally (T), or not (NA) | string | | | |


# Examples

# VRT

```{r}


```

# OpenDAP

# STAC
